### PR TITLE
Add Host to RSS Link

### LINKED ISSUE #17: RSS Posts Links should be fully qualified.
As it means you can't click on the links in your reader - it thinks they're at the same domain name as the reader.

I've been working on a patch, but am having problems bending Buffalo to my will - will keep trying and submit when I have a moment.

### PR DESCRIPTION
**Pull request by darron**
This would close #17.

### CODE REVIEW

**Comment by bscott** [comment]
this was merged manually into master

**Comment by bscott** [comment]
@darron was this tested as I see RSS links are still broken?

**Comment by darron** [comment]
I did test it. When I looked at the RSS earlier today it didn't look like
the change was deployed and live.

Did it get deployed?

**Comment by darron** [comment]
Looks good now @bscott - they're showing up now. Thanks!

**Pull request closed without merging**
